name: Fortran auto format

on:
  push:
    branches:
      - main
    paths:
      - src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install fprettify
        run: pip install fprettify

      - name: apply fprettify
        run: fprettify -i 2 -r src/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
